### ISSUE TITLE
antialiasing and video output

### ISSUE THREAD

**Issue by sfmth** [MarcPartensky/Fourier#4]
Have you tried using [pygame.gfxdraw](http://www.pygame.org/docs/ref/gfxdraw.html) for smooth shapes?
And also is there a way to get video output of the drawing? Sharing the work is all the fun

**Comment by MarcPartensky** [comment]
No I haven't tried using pygame.gfxdraw. Does it really make better shapes?
And no sorry, there is no built in option to record the video. You have use a screen recorder for that, at least for now.
I'd recommend you to record the video while in fullscreen. The simulation is built so that it will resize automatically.

Btw, if you find an easy way to record screen with opencv, pull requests are welcome.

**Comment by sfmth** [comment]
How can I initiate typing mode? 
I play Minecraft too
